# Generated by Django 5.1.6 on 2025-06-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_comment_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkboxingredient',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='checkboxingredient',
            name='category',
            field=models.CharField(choices=[('MEAT', 'Meat'), ('VEG', 'Veggies'), ('FRUIT', 'Fruits'), ('DAIRY', 'Dairy'), ('OTHER', 'Other')], default='OTHER', help_text='Select the category for this ingredient.', max_length=20),
        ),
    ]
