# Generated by Django 5.1.6 on 2025-06-11 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_checkboxingredient_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cookingtime',
            options={'ordering': ['time_in_minutes']},
        ),
    ]
